### PR TITLE
fix undefs

### LINKED ISSUE #17: Undefined index: whereColumn
```
            [
                'type' => 'python',
                'backend' => 'docker',
                'input' => [
                    [
                        'source' => 'in.c-main.source',
                        'destination' => 'destination.csv',
                    ],
                    [
                        'source' => 'in.c-main.source',
                        'destination' => 'destination.csv',
                        'whereColumn' => 'id',
                        'whereOperator' => 'eq',
                        'whereValues' => ['68640847'],
                    ],
                ],
                'tags' => ['my-file'],
                'queries' => [
                    "this is some script\ncode on multiple lines",
                ],
            ]
```

### PR DESCRIPTION
**Pull request by odinuv**
fixes https://github.com/keboola/data-loader/issues/17

### CODE REVIEW

File: tests/functional/TransformationSandboxTest.php [hunk 1]
```diff
@@ -122,6 +122,69 @@ public function testTables(): void
...
+                ' app-logger.INFO: Loaded transformation script (size 43).  ',
+                ' app-logger.INFO: There are no input files.  ',
+                ' app-logger.INFO: Fetched table in.c-main.source.  ',
+                ' app-logger.INFO: Processing 1 table exports.  ',
+                ' app-logger.INFO: All tables were fetched.  ',
+                '',
+            ]),
+            $output
+        );
+        $this->components->deleteConfiguration('transformation', $vars['configId']);
```
Comment (pivnicek) [inline tests/functional/TransformationSandboxTest.php]: I think this is taken care of in setup() since last PR

File: tests/phpunit/ExportConfigTest.php [hunk 2]
```diff
@@ -29,7 +29,14 @@ public function configurationProvider(): array
...
                 [],
-                [],
+                [
+                    'storage' => [
+                        'input' => [
+                            'files' => [],
+                            'tables' => [],
+                        ],
+                    ],
+                ],
```
Comment (pivnicek) [inline tests/phpunit/ExportConfigTest.php:39]: ah, I see, this is because of the new `addDefaultIfNotSet`.  👍

**Review by pivnicek — APPROVED** [review]
Looks good,  I think we should update the README though to mention the .env setup and that the project needs to have an `in.c-main` bucket, or create one at the beginning or something

File: tests/functional/TransformationSandboxTest.php (hunk 1 above)
Comment (odinuv) [reply tests/functional/TransformationSandboxTest.php]: sure! completely missed that
