### PR TITLE
support fix

### LINKED ISSUE #18: remove support email

### PR DESCRIPTION
**Pull request by odinuv**
fixes: #18 
master issue https://github.com/keboola/internal/issues/34

### CODE REVIEW

File: src/StorageApiHandler.php [hunk 1]
```diff
@@ -49,7 +49,7 @@ public function handle(array $record): bool
             case Logger::ALERT:
                 $type = Event::TYPE_ERROR;
                 $event->setMessage('Application error');
-                $event->setDescription('Contact support@keboola.com');
+                $event->setDescription('Please contact the support for help.');
```
Comment (pivnicek) [inline src/StorageApiHandler.php]: maybe `Please contact Keboola Support for help`?

**Review by pivnicek — CHANGES_REQUESTED** [review]
minor text change

**Comment by odinuv** [comment]
done -> merging
